version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: python /codebase/server.py
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always
